POST http://localhost:3001/create HTTP/1.1
Content-type: application/json

    {
    "tipo": "cartao",
    "nome": "Seu Nome",
    "numero": "1234567890123456",
    "validade": "12/25",
    "cvv": "123"
    }


###

POST http://localhost:3001/create HTTP/1.1
Content-type: application/json

    {
    "tipo": "pix",
    "nome": "Gabriel Henrique",
    "chave": "emaildeexemplo@exemplo.com"
    }

###

POST http://localhost:3001/create HTTP/1.1
Content-type: application/json

    {
    "tipo": "boleto",
    "nome": "Camila Camargo",
    "valor": 100.00
    }


###

GET http://localhost:3001/show HTTP/1.1
Content-type: application/json

###

GET http://localhost:3001/read/2 HTTP/1.1
Content-type: application/json

###

PUT http://localhost:3001/update/2 HTTP/1.1
Content-type: application/json

    {
        "nome": "Otavio Lopes Dias",
        "numero": 1234567890123456,
        "validade": "12/25",
        "cvv": "123"
    }

###

DELETE http://localhost:3001/delete/2 HTTP/1.1
content-type: application/json