POST http://localhost:3000/quadras HTTP/1.1
Content-type: application/json

{
    "quadra":"pquadra",
    "disponivel":"pdisponivel",
    "tempo":"ptempo",
    "largura":"plargura",
    "comprimento":"pcomprimento",
    "equipamentos":"pequipamentos"
}    

###
GET  http://localhost:3000/quadras HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:3000/quadras/3 HTTP/1.1
Content-Type: application/json

{
    "quadra":"quadra 1",
    "disponivel":"disponivel",
    "tempo":"tempo",
    "largura":"largura",
    "comprimento":"comprimento",
    "equipamentos":"equipamentos"
}    

