POST http://localhost:4000/quadra/create HTTP/1.1
Content-type: application/json

{
    "quadra":"quadra da vila nery",
    "disponivel":"sim",
    "tempo":"1h",
    "largura":"11",
    "comprimento":"25",
    "equipamentos":"bola, rede"
}    

###
GET  http://localhost:4000/quadras?preco_min=100&preco_max=300 HTTP/1.1
Content-Type: application/json

###
GET  http://localhost:4000/quadra/show/2 HTTP/1.1
Content-Type: application/json

###
DELETE  http://localhost:4000/quadra/delete/1 HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:4000/quadra/update/2 HTTP/1.1
Content-Type: application/json

{
    "disponivel":"não"
}    




