POST http://192.168.49.214:3000/user/create HTTP/1.1
content-type: application/json


{
    "genero": "Masculino",
    "idade": "26",
    "nome": "Eduardo"
}


###


GET http://192.168.49.214:3000/user/read HTTP/1.1
content-type: application/json


###


GET http://192.168.49.214:3000/user/show/3 HTTP/1.1
content-type: application/json



###

PUT http://192.168.49.214:3000/user/update/3 HTTP/1.1
content-type: application/json


{
    "genero": "Feminino",
    "idade": "25",
    "nome": "Elisa"
}

###


DELETE http://192.168.49.214:3000/user/delete/1 HTTP/1.1
content-type: application/json